version: '3.9'

services:
  localstack:
    container_name: localstack-sls
    image: localstack/localstack:1.2
    restart: on-failure
    ports:
      - "4566:4566"   # LocalStack Gateway
    environment:
      - DOCKER_HOST=unix:///var/run/docker.sock
    volumes:
      - "${LOCALSTACK_VOLUME_DIR:-./volume}:/var/lib/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"

#  app:
#    container_name: serverless-app
#    restart: on-failure
#    build: .
#    volumes:
#      - .:/src
#      - nodemodules:/src/node_modules
#    ports:
#      - 3000:3000
#    links:
#      - localstack
#    depends_on:
#      - localstack
#    environment:
#      LOCALSTACK_HOST: localstack
#      DYNAMODB_PORT: 4566
#      NODE_ENV: "development"

#  test:
#    container_name: serverless-test
#    build: .
#    command:
#      - yarn test
#    volumes:
#      - .:/src
#      - nodemodules:/src/node_modules
#    restart: on-failure
#    links:
#      - localstack
#    depends_on:
#      - localstack
#    environment:
#      LOCALSTACK_HOST: localstack
#      DYNAMODB_PORT: 4566
#      NODE_ENV: "development"

volumes:
  nodemodules: {}
